{"hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/error"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/snowplowtracker\/trackererror\/error"]}],"metadata":{"title":"error","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","modules":[{"name":"SnowplowTracker"}],"externalID":"c:@M@SnowplowTracker@objc(cs)SPTrackerError(py)error"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Error involved in the error."}],"references":{"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError":{"kind":"symbol","type":"topic","title":"TrackerError","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TrackerError"}],"navigatorTitle":[{"kind":"identifier","text":"TrackerError"}],"role":"symbol","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError","abstract":[{"type":"text","text":"Tracker error event used in diagnostic autotracking."}],"url":"\/documentation\/snowplowtracker\/trackererror"},"doc://SnowplowTracker/documentation/SnowplowTracker":{"kind":"symbol","type":"topic","abstract":[],"role":"collection","title":"SnowplowTracker","url":"\/documentation\/snowplowtracker","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker"},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError/error":{"kind":"symbol","type":"topic","title":"error","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/error","abstract":[{"type":"text","text":"Error involved in the error."}],"url":"\/documentation\/snowplowtracker\/trackererror\/error"}}}