{"sections":[],"abstract":[{"type":"text","text":"Error involved in the error."}],"metadata":{"modules":[{"name":"SnowplowTracker"}],"roleHeading":"Instance Property","symbolKind":"property","title":"error","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"externalID":"c:@M@SnowplowTracker@objc(cs)SPTrackerError(py)error","role":"symbol"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/snowplowtracker\/trackererror\/error"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?","kind":"text"}],"platforms":["macOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/error"},"references":{"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError":{"url":"\/documentation\/snowplowtracker\/trackererror","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TrackerError","kind":"identifier"}],"navigatorTitle":[{"text":"TrackerError","kind":"identifier"}],"kind":"symbol","title":"TrackerError","role":"symbol","abstract":[{"type":"text","text":"Tracker error event used in diagnostic autotracking."}],"type":"topic"},"doc://SnowplowTracker/documentation/SnowplowTracker":{"url":"\/documentation\/snowplowtracker","role":"collection","abstract":[],"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","type":"topic","title":"SnowplowTracker","kind":"symbol"},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError/error":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[{"text":"Error involved in the error.","type":"text"}],"url":"\/documentation\/snowplowtracker\/trackererror\/error","kind":"symbol","title":"error","type":"topic","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/error"}}}