{"hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/error"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Error involved in the error."}],"metadata":{"modules":[{"name":"SnowplowTracker"}],"title":"error","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@SnowplowTracker@objc(cs)SPTrackerError(py)error"},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/snowplowtracker\/trackererror\/error"]}],"references":{"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError","url":"\/documentation\/snowplowtracker\/trackererror","type":"topic","title":"TrackerError","navigatorTitle":[{"text":"TrackerError","kind":"identifier"}],"abstract":[{"text":"Tracker error event used in diagnostic autotracking.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TrackerError"}]},"doc://SnowplowTracker/documentation/SnowplowTracker":{"url":"\/documentation\/snowplowtracker","abstract":[],"title":"SnowplowTracker","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker"},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError/error":{"kind":"symbol","title":"error","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/snowplowtracker\/trackererror\/error","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Error involved in the error."}],"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/error"}}}