{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"platforms":["macOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/error"},"metadata":{"role":"symbol","roleHeading":"Instance Property","title":"error","externalID":"c:@M@SnowplowTracker@objc(cs)SPTrackerError(py)error","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?","kind":"text"}],"modules":[{"name":"SnowplowTracker"}],"symbolKind":"property"},"variants":[{"paths":["\/documentation\/snowplowtracker\/trackererror\/error"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","abstract":[{"text":"Error involved in the error.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError/error":{"title":"error","url":"\/documentation\/snowplowtracker\/trackererror\/error","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/error","abstract":[{"text":"Error involved in the error.","type":"text"}],"type":"topic"},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError":{"title":"TrackerError","url":"\/documentation\/snowplowtracker\/trackererror","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TrackerError","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError","abstract":[{"text":"Tracker error event used in diagnostic autotracking.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TrackerError"}],"type":"topic"},"doc://SnowplowTracker/documentation/SnowplowTracker":{"url":"\/documentation\/snowplowtracker","role":"collection","type":"topic","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","abstract":[],"title":"SnowplowTracker","kind":"symbol"}}}