{"kind":"symbol","abstract":[{"type":"text","text":"Error involved in the error."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/error"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"error","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:@M@SnowplowTracker@objc(cs)SPTrackerError(py)error","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"SnowplowTracker"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/snowplowtracker\/trackererror\/error"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError"]]},"references":{"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError/error":{"title":"error","role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Error involved in the error."}],"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/error","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?"}],"url":"\/documentation\/snowplowtracker\/trackererror\/error"},"doc://SnowplowTracker/documentation/SnowplowTracker":{"title":"SnowplowTracker","role":"collection","kind":"symbol","abstract":[],"url":"\/documentation\/snowplowtracker","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","type":"topic"},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TrackerError"}],"navigatorTitle":[{"kind":"identifier","text":"TrackerError"}],"type":"topic","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError","abstract":[{"type":"text","text":"Tracker error event used in diagnostic autotracking."}],"title":"TrackerError","url":"\/documentation\/snowplowtracker\/trackererror","kind":"symbol"}}}