{"metadata":{"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"error","modules":[{"name":"SnowplowTracker"}],"externalID":"c:@M@SnowplowTracker@objc(cs)SPTrackerError(py)error"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/snowplowtracker\/trackererror\/error"]}],"abstract":[{"type":"text","text":"Error involved in the error."}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/error","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError"]]},"references":{"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError":{"kind":"symbol","navigatorTitle":[{"text":"TrackerError","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Tracker error event used in diagnostic autotracking."}],"url":"\/documentation\/snowplowtracker\/trackererror","title":"TrackerError","role":"symbol","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TrackerError","kind":"identifier"}]},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError/error":{"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/error","url":"\/documentation\/snowplowtracker\/trackererror\/error","role":"symbol","abstract":[{"text":"Error involved in the error.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?","kind":"text"}],"type":"topic","title":"error"},"doc://SnowplowTracker/documentation/SnowplowTracker":{"title":"SnowplowTracker","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","role":"collection","kind":"symbol","url":"\/documentation\/snowplowtracker","type":"topic","abstract":[]}}}