{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/message","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Message of the error."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"message"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/snowplowtracker\/trackererror\/message"]}],"metadata":{"title":"message","symbolKind":"property","modules":[{"name":"SnowplowTracker"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@SnowplowTracker@objc(cs)SPTrackerError(py)message","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"sections":[],"kind":"symbol","references":{"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError/message":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/message","abstract":[{"type":"text","text":"Message of the error."}],"title":"message","url":"\/documentation\/snowplowtracker\/trackererror\/message","kind":"symbol"},"doc://SnowplowTracker/documentation/SnowplowTracker":{"title":"SnowplowTracker","role":"collection","kind":"symbol","abstract":[],"url":"\/documentation\/snowplowtracker","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","type":"topic"},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TrackerError"}],"navigatorTitle":[{"kind":"identifier","text":"TrackerError"}],"type":"topic","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError","abstract":[{"type":"text","text":"Tracker error event used in diagnostic autotracking."}],"title":"TrackerError","url":"\/documentation\/snowplowtracker\/trackererror","kind":"symbol"}}}