{"metadata":{"title":"message","roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@SnowplowTracker@objc(cs)SPTrackerError(py)message","role":"symbol","modules":[{"name":"SnowplowTracker"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/snowplowtracker\/trackererror\/message"]}],"identifier":{"url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/message","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Message of the error.","type":"text"}],"sections":[],"references":{"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError/message":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"type":"text","text":"Message of the error."}],"kind":"symbol","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/message","url":"\/documentation\/snowplowtracker\/trackererror\/message","title":"message","role":"symbol","type":"topic"},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError":{"title":"TrackerError","url":"\/documentation\/snowplowtracker\/trackererror","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TrackerError","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError","abstract":[{"text":"Tracker error event used in diagnostic autotracking.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TrackerError"}],"type":"topic"},"doc://SnowplowTracker/documentation/SnowplowTracker":{"url":"\/documentation\/snowplowtracker","role":"collection","type":"topic","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","abstract":[],"title":"SnowplowTracker","kind":"symbol"}}}