{"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","role":"symbol","title":"message","externalID":"c:@M@SnowplowTracker@objc(cs)SPTrackerError(py)message","symbolKind":"property","modules":[{"name":"SnowplowTracker"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/message"},"hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/snowplowtracker\/trackererror\/message"]}],"sections":[],"abstract":[{"text":"Message of the error.","type":"text"}],"references":{"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError/message":{"kind":"symbol","title":"message","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/snowplowtracker\/trackererror\/message","type":"topic","role":"symbol","abstract":[{"text":"Message of the error.","type":"text"}],"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/message"},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError","url":"\/documentation\/snowplowtracker\/trackererror","type":"topic","title":"TrackerError","navigatorTitle":[{"text":"TrackerError","kind":"identifier"}],"abstract":[{"text":"Tracker error event used in diagnostic autotracking.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TrackerError"}]},"doc://SnowplowTracker/documentation/SnowplowTracker":{"url":"\/documentation\/snowplowtracker","abstract":[],"title":"SnowplowTracker","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker"}}}