{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"platforms":["macOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"message","role":"symbol","symbolKind":"property","externalID":"c:@M@SnowplowTracker@objc(cs)SPTrackerError(py)message","modules":[{"name":"SnowplowTracker"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError"]]},"abstract":[{"type":"text","text":"Message of the error."}],"identifier":{"url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/message","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/snowplowtracker\/trackererror\/message"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"references":{"doc://SnowplowTracker/documentation/SnowplowTracker":{"url":"\/documentation\/snowplowtracker","role":"collection","abstract":[],"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","type":"topic","title":"SnowplowTracker","kind":"symbol"},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError":{"url":"\/documentation\/snowplowtracker\/trackererror","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TrackerError","kind":"identifier"}],"navigatorTitle":[{"text":"TrackerError","kind":"identifier"}],"kind":"symbol","title":"TrackerError","role":"symbol","abstract":[{"type":"text","text":"Tracker error event used in diagnostic autotracking."}],"type":"topic"},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError/message":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","title":"message","url":"\/documentation\/snowplowtracker\/trackererror\/message","abstract":[{"text":"Message of the error.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/message"}}}