{"abstract":[{"text":"Message of the error.","type":"text"}],"kind":"symbol","variants":[{"paths":["\/documentation\/snowplowtracker\/trackererror\/message"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError"]]},"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@SnowplowTracker@objc(cs)SPTrackerError(py)message","title":"message","modules":[{"name":"SnowplowTracker"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"symbolKind":"property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/message"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://SnowplowTracker/documentation/SnowplowTracker":{"title":"SnowplowTracker","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","url":"\/documentation\/snowplowtracker","abstract":[]},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError/message":{"title":"message","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/message","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"message","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Message of the error."}],"role":"symbol","type":"topic","url":"\/documentation\/snowplowtracker\/trackererror\/message"},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError":{"navigatorTitle":[{"kind":"identifier","text":"TrackerError"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TrackerError"}],"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError","url":"\/documentation\/snowplowtracker\/trackererror","title":"TrackerError","abstract":[{"type":"text","text":"Tracker error event used in diagnostic autotracking."}],"kind":"symbol"}}}