{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/source"},"metadata":{"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SnowplowTracker@objc(cs)SPTrackerError(py)source","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"source","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"modules":[{"name":"SnowplowTracker"}],"title":"source"},"abstract":[{"text":"Class name or source where the error appeared.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/snowplowtracker\/trackererror\/source"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"source","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}]}],"hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError"]]},"references":{"doc://SnowplowTracker/documentation/SnowplowTracker":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/snowplowtracker","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","abstract":[],"title":"SnowplowTracker"},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError/source":{"type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Class name or source where the error appeared.","type":"text"}],"url":"\/documentation\/snowplowtracker\/trackererror\/source","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"source"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/source","title":"source"},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError":{"url":"\/documentation\/snowplowtracker\/trackererror","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TrackerError","kind":"identifier"}],"navigatorTitle":[{"text":"TrackerError","kind":"identifier"}],"abstract":[{"type":"text","text":"Tracker error event used in diagnostic autotracking."}],"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError","kind":"symbol","type":"topic","title":"TrackerError","role":"symbol"}}}