{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"source","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/snowplowtracker\/trackererror\/source"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"SnowplowTracker"}],"role":"symbol","externalID":"c:@M@SnowplowTracker@objc(cs)SPTrackerError(py)source","symbolKind":"property","title":"source","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"source"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"abstract":[{"text":"Class name or source where the error appeared.","type":"text"}],"identifier":{"url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/source","interfaceLanguage":"swift"},"references":{"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError/source":{"kind":"symbol","role":"symbol","title":"source","type":"topic","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/source","url":"\/documentation\/snowplowtracker\/trackererror\/source","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"source","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Class name or source where the error appeared."}]},"doc://SnowplowTracker/documentation/SnowplowTracker":{"abstract":[],"type":"topic","kind":"symbol","title":"SnowplowTracker","role":"collection","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","url":"\/documentation\/snowplowtracker"},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError":{"url":"\/documentation\/snowplowtracker\/trackererror","abstract":[{"type":"text","text":"Tracker error event used in diagnostic autotracking."}],"navigatorTitle":[{"text":"TrackerError","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TrackerError","kind":"identifier"}],"type":"topic","title":"TrackerError"}}}