{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"source","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]}]}],"hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError"]]},"abstract":[{"text":"Class name or source where the error appeared.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/source"},"sections":[],"metadata":{"title":"source","role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"source","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"modules":[{"name":"SnowplowTracker"}],"roleHeading":"Instance Property","externalID":"c:@M@SnowplowTracker@objc(cs)SPTrackerError(py)source"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/snowplowtracker\/trackererror\/source"]}],"references":{"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError":{"navigatorTitle":[{"kind":"identifier","text":"TrackerError"}],"kind":"symbol","title":"TrackerError","url":"\/documentation\/snowplowtracker\/trackererror","type":"topic","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError","abstract":[{"type":"text","text":"Tracker error event used in diagnostic autotracking."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TrackerError","kind":"identifier"}],"role":"symbol"},"doc://SnowplowTracker/documentation/SnowplowTracker":{"type":"topic","title":"SnowplowTracker","abstract":[],"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","kind":"symbol","url":"\/documentation\/snowplowtracker","role":"collection"},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError/source":{"kind":"symbol","abstract":[{"type":"text","text":"Class name or source where the error appeared."}],"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/source","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"source","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"source","role":"symbol","url":"\/documentation\/snowplowtracker\/trackererror\/source"}}}