{"identifier":{"url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/source","interfaceLanguage":"swift"},"metadata":{"title":"source","roleHeading":"Instance Property","modules":[{"name":"SnowplowTracker"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"source","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@SnowplowTracker@objc(cs)SPTrackerError(py)source"},"variants":[{"paths":["\/documentation\/snowplowtracker\/trackererror\/source"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"source"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Class name or source where the error appeared.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError":{"navigatorTitle":[{"kind":"identifier","text":"TrackerError"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TrackerError"}],"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError","url":"\/documentation\/snowplowtracker\/trackererror","title":"TrackerError","abstract":[{"type":"text","text":"Tracker error event used in diagnostic autotracking."}],"kind":"symbol"},"doc://SnowplowTracker/documentation/SnowplowTracker":{"title":"SnowplowTracker","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","url":"\/documentation\/snowplowtracker","abstract":[]},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError/source":{"title":"source","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/source","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"source"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Class name or source where the error appeared."}],"role":"symbol","type":"topic","url":"\/documentation\/snowplowtracker\/trackererror\/source"}}}