{"kind":"symbol","variants":[{"paths":["\/documentation\/snowplowtracker\/trackererror\/source"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"source"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"languages":["swift"]}]}],"sections":[],"metadata":{"title":"source","roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@SnowplowTracker@objc(cs)SPTrackerError(py)source","role":"symbol","modules":[{"name":"SnowplowTracker"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"source","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/source"},"abstract":[{"text":"Class name or source where the error appeared.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError"]]},"references":{"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError/source":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"source"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Class name or source where the error appeared."}],"kind":"symbol","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/source","url":"\/documentation\/snowplowtracker\/trackererror\/source","title":"source","role":"symbol","type":"topic"},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError":{"title":"TrackerError","url":"\/documentation\/snowplowtracker\/trackererror","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TrackerError","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError","abstract":[{"text":"Tracker error event used in diagnostic autotracking.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TrackerError"}],"type":"topic"},"doc://SnowplowTracker/documentation/SnowplowTracker":{"url":"\/documentation\/snowplowtracker","role":"collection","type":"topic","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","abstract":[],"title":"SnowplowTracker","kind":"symbol"}}}