{"metadata":{"modules":[{"name":"SnowplowTracker"}],"role":"symbol","title":"source","externalID":"c:@M@SnowplowTracker@objc(cs)SPTrackerError(py)source","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"source","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/snowplowtracker\/trackererror\/source"]}],"identifier":{"url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/source","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"text":"Class name or source where the error appeared.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"source"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}],"kind":"declarations"}],"references":{"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError":{"url":"\/documentation\/snowplowtracker\/trackererror","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TrackerError","kind":"identifier"}],"navigatorTitle":[{"text":"TrackerError","kind":"identifier"}],"kind":"symbol","title":"TrackerError","role":"symbol","abstract":[{"type":"text","text":"Tracker error event used in diagnostic autotracking."}],"type":"topic"},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError/source":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","abstract":[{"text":"Class name or source where the error appeared.","type":"text"}],"url":"\/documentation\/snowplowtracker\/trackererror\/source","kind":"symbol","title":"source","type":"topic","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/source"},"doc://SnowplowTracker/documentation/SnowplowTracker":{"url":"\/documentation\/snowplowtracker","role":"collection","abstract":[],"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","type":"topic","title":"SnowplowTracker","kind":"symbol"}}}